name: CI

on: [push]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Tox install
        run:
          pip install tox tox-gh-actions

      - name: Test with tox
        run: tox

     # - name: Test with pytest
     #   env:
     #     DJANGO_SETTINGS_MODULE: MainProject.settings
     #   run: poetry run pytest --cov . -n 2
